"""empty message

Revision ID: e6d7805630e3
Revises: 
Create Date: 2026-06-01 12:25:21.451085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d7805630e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(), nullable=True),
    sa.Column('animal_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('animal_id')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animals_animal_count'), ['animal_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_animal_type'), ['animal_type'], unique=False)

    op.create_table('dangers',
    sa.Column('danger_id', sa.Integer(), nullable=False),
    sa.Column('danger_spec', sa.String(), nullable=True),
    sa.Column('danger_detect', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('danger_id')
    )
    with op.batch_alter_table('dangers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dangers_danger_spec'), ['danger_spec'], unique=False)

    op.create_table('detect_animal',
    sa.Column('detect_id', sa.Integer(), nullable=False),
    sa.Column('detect_type_count', sa.String(), nullable=True),
    sa.Column('detect_animal_count', sa.Integer(), nullable=True),
    sa.Column('detect_day', sa.DateTime(), nullable=True),
    sa.Column('detect_alarm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('detect_id')
    )
    with op.batch_alter_table('detect_animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detect_animal_detect_animal_count'), ['detect_animal_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_detect_animal_detect_type_count'), ['detect_type_count'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='user', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('detect_animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detect_animal_detect_type_count'))
        batch_op.drop_index(batch_op.f('ix_detect_animal_detect_animal_count'))

    op.drop_table('detect_animal')
    with op.batch_alter_table('dangers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dangers_danger_spec'))

    op.drop_table('dangers')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_animal_type'))
        batch_op.drop_index(batch_op.f('ix_animals_animal_count'))

    op.drop_table('animals')
    # ### end Alembic commands ###
